# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appc < Formula
  desc "App Store Connect API CLI tool"
  homepage "https://github.com/tadaken3/appc"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.3/appc_darwin_amd64.tar.gz"
      sha256 "0a5c9a5917db3e08e7d56ee0fada00745fab1a7c6ac9f52a8c3e46b5702b4d0b"

      def install
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.3/appc_darwin_arm64.tar.gz"
      sha256 "9cbbbefce5e57edbbf725219df0109700b8f2d0d223c6de4ce50a362231798c2"

      def install
        bin.install "appc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.3/appc_linux_amd64.tar.gz"
      sha256 "3331c67c8b64c4d4dbeaee06c52bd0aa2c6e7fb1be4d10b6bcd2c36ed7b88b54"
      def install
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.3/appc_linux_arm64.tar.gz"
      sha256 "ba93a3d613f23f00d7176c3e24df2f4e084c387273559ae8306f7568b9ad3458"
      def install
        bin.install "appc"
      end
    end
  end

  test do
    system "#{bin}/appc", "--help"
  end
end
