# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appc < Formula
  desc "App Store Connect API CLI tool"
  homepage "https://github.com/tadaken3/appc"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.2/appc_darwin_amd64.tar.gz"
      sha256 "de7e519b5d7646bf469fe9f9812a9988b2c26f53aca4a105a00cdddb36626397"

      def install
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.2/appc_darwin_arm64.tar.gz"
      sha256 "ec3a7d370ed306ef7980b1415d17f836ce62659e8f580dead79c91aa45d365f6"

      def install
        bin.install "appc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.2/appc_linux_amd64.tar.gz"
      sha256 "6a9a3437dd3c5f256c67876a82a7ab6aa77d28634061db84c0a58e335ba1e807"
      def install
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.0.2/appc_linux_arm64.tar.gz"
      sha256 "64f10f14c929aed1240be47b0a28b74fd22333243e6187c87edfc7b9ede54afc"
      def install
        bin.install "appc"
      end
    end
  end

  test do
    system "#{bin}/appc", "--help"
  end
end
