# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appc < Formula
  desc "App Store Connect API CLI tool"
  homepage "https://github.com/tadaken3/appc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tadaken3/appc/releases/download/v0.1.0/appc_darwin_amd64.tar.gz"
      sha256 "36d8d2d4d71c98fc5fc37753c66f0a90f48f899d9f612770fd106ca028fa3f19"

      define_method(:install) do
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tadaken3/appc/releases/download/v0.1.0/appc_darwin_arm64.tar.gz"
      sha256 "7761ee09497055ea0d79949bb703067924e3bb5b4f811d53461455acda25b56b"

      define_method(:install) do
        bin.install "appc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.1.0/appc_linux_amd64.tar.gz"
      sha256 "7879095cc86c3b9d801533dff1084fb26c0a11c90009d90c3ebc98d2e19b7e31"
      define_method(:install) do
        bin.install "appc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tadaken3/appc/releases/download/v0.1.0/appc_linux_arm64.tar.gz"
      sha256 "63603d6dfe0e90f2fa8030a55ba30dc36da59dfcf1152f86dc1019c13fc872d0"
      define_method(:install) do
        bin.install "appc"
      end
    end
  end

  test do
    system "#{bin}/appc", "--help"
  end
end
